### ISSUE TITLE
Make AuthToken optional as a command-line argument

### ISSUE THREAD

**Issue by karate** [schickling/docker-hook#12]
Giving the AuthToken as a command-line argument is not very secure, because it's visible in `top`, `w` and `history`. You could make the AuthToken argument optional, and fallback to a hardcoded value inside the scipt. So someone could put their AuthToken in the script, and call the script with
```
$ docker-hook -c <command>
```

I can make a PR if you're ok with it

**Comment by schickling** [comment]
How about an env variable instead? Happy to merge a PR.
