### ISSUE TITLE
Docs are inconsistent with current script

### ISSUE THREAD

**Issue by MartinThoma** [schickling/docker-hook#5]
The README says the way to use docker-hook is

> docker-hook my-super-safe-token ./deploy.sh

But you need to call it like

> docker-hook -t my-super-safe-token -c ./deploy.sh

If you really want to have it without named arguments (but positional arguments), just remove the name (hence removing `required=True` and `"-t", "--token",` and `"-c", "--cmd"`.

But I really like named arguments. It makes stuff much clearer.

**Comment by schickling** [comment]
You're absolutely right. I added you as a collaborator. :+1:

**Comment by MartinThoma** [comment]
Fixed with 9eba9caebe2160a67ca7cb66af64cf4fc1439170 :-)
